# Generated by Django 3.2.3 on 2024-08-06 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('climate', models.CharField(blank=True, max_length=255, null=True)),
                ('diameter', models.IntegerField(blank=True, null=True)),
                ('orbital_period', models.IntegerField(blank=True, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('rotation_period', models.IntegerField(blank=True, null=True)),
                ('surface_water', models.FloatField(blank=True, null=True)),
                ('terrain', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Planets',
                'db_table': 'ex10_planets',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('birth_year', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.CharField(blank=True, max_length=32, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=32, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=32, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('homeworld', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ex10.planets')),
            ],
            options={
                'verbose_name_plural': 'People',
                'db_table': 'ex10_people',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('episode_nb', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('opening_crawl', models.TextField(blank=True, null=True)),
                ('director', models.CharField(max_length=32)),
                ('producer', models.CharField(max_length=128)),
                ('release_date', models.DateField()),
                ('characters', models.ManyToManyField(related_name='movies', to='ex10.People')),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'db_table': 'ex10_movies',
            },
        ),
    ]
