# Generated by Django 3.2.3 on 2024-07-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex01', '0002_alter_movies_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={},
        ),
        migrations.AlterField(
            model_name='movies',
            name='episode_nb',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='movies',
            table='ex01_movies',
        ),
    ]
