# Generated by Django 3.2.3 on 2024-08-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_auto_20240808_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
