# Generated by Django 3.2.3 on 2024-08-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0004_auto_20240808_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
