# Generated by Django 3.2.3 on 2024-08-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0005_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='ex_customuser',
        ),
    ]
