# Generated by Django 3.2.3 on 2024-08-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0007_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
