# Generated by Django 3.2.3 on 2024-08-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0009_auto_20240808_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tip_admin',
            field=models.BooleanField(default=False),
        ),
    ]
