# Generated by Django 3.2.3 on 2024-08-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0010_customuser_is_tip_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tip_downvoter',
            field=models.BooleanField(default=False),
        ),
    ]
