# Generated by Django 3.2.3 on 2024-08-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0012_auto_20240809_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tip_admin_remover',
            field=models.BooleanField(default=False),
        ),
    ]
