# Generated by Django 3.2.3 on 2024-08-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0013_customuser_is_tip_admin_remover'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tip_admin_downvoter',
            field=models.BooleanField(default=False),
        ),
    ]
