# Generated by Django 3.2.3 on 2024-08-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0014_customuser_is_tip_admin_downvoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
