# Generated by Django 3.2.3 on 2024-08-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0016_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
