# Generated by Django 3.2.3 on 2024-08-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0004_alter_people_homeworld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
