# Generated by Django 3.2.3 on 2024-08-06 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0005_alter_people_homeworld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(max_length=68, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ex09.planets'),
        ),
    ]
