services:
    d09_database:
        image: postgres:latest
        env_file: .env
        container_name: ${DATABASE_CONTAINER}
        environment:
            POSTGRES_DB: ${DATABASE_DB}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "${DATABASE_HOST_PORT}:${DATABASE_CONTAINER_PORT}"
        volumes:
            - ${DATABASE_VOLUME}:/var/lib/postgresql/data
        networks:
            - ${NETWORK}
    
    d09_redis:
        image: redis:7
        env_file: .env
        container_name: ${REDIS_CONTAINER}
        ports:
            - "${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}"
        networks:
            - ${NETWORK}

volumes:
    d09_volume:
        driver: local

networks:
    d09_network:
        driver: bridge
