services:
    d06_database:
        image: postgres:latest
        env_file: .env
        container_name: ${DATABASE_CONTAINER}
        environment:
            POSTGRES_DB: ${DATABASE_DB}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "${DATABASE_HOST_PORT}:${DATABASE_CONTAINER_PORT}"
        volumes:
            - ${DATABASE_VOLUME}:/var/lib/postgresql/data
        networks:
            - ${DATABASE_NETWORK}

volumes:
    d06_volume:
        driver: local

networks:
    d06_network:
        driver: bridge
